version: '3.5'

services:
  pg:
    tty: true
    container_name: postgres
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
      POSTGRES_DB: sandbox
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
    volumes:
      - ./work:/docker-entrypoint-initdb.d/
      - ./postgres:/data/postgres
    ports:
      - "25432:5432"
    restart: always
    networks:
      - default
      - shared-network
networks:
  shared-network:
    external: true